fix curt when not recording
Oops.  Recent recording changes broke the non-recording use:
--
$ ./curt.py --debug
Relaunching under "perf" command...
['perf', 'script', '-i', [], '-s', './curt.py', '--', '--window', '20', '--debug', '--api', '1']
Traceback (most recent call last):
  File "./curt.py", line 113, in <module>
    os.execvp("perf", sys.argv)
  File "/usr/lib64/python2.7/os.py", line 344, in execvp
    _execvpe(file, args)
  File "/usr/lib64/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
TypeError: execv() arg 2 must contain only strings
--

The "params.file_or_command" variable is a list, so instead of embedding it,
it should be concatenated.

Signed-off-by: Paul A. Clarke <pc@us.ibm.com>